services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper-api
    ports:
      - "8080:8080"
    volumes:
      - scraper-data:/app/data
    command: [
      "./scraper-api",
      "-addr", ":8080",
      "-db", "/app/data/scraper.db",
      "-ollama-url", "http://honker:11434",
      "-ollama-model", "gpt-oss:20b"
    ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  scraper-data:
    driver: local

networks:
  default:
    name: scraper-network
