services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper-api
    ports:
      - "8080:8080"
    volumes:
      - scraper-data:/app/data
    environment:
      - PORT=8080
      - DB_PATH=/app/data/scraper.db
      - OLLAMA_URL=http://100.64.0.2:11434
      - OLLAMA_MODEL=gpt-oss:20b
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  scraper-data:
    driver: local

networks:
  default:
    name: scraper-network
